### ISSUE TITLE
Undefined index PHP notice in LtiDeepLink.php

### ISSUE THREAD

**Issue by mattwright** [packbackbooks/lti-1-3-php-library#43]
My server is occasionally throwing the following PHP warning:

PHP message: PHP Notice:  Undefined index: data in /.../vendor/packbackbooks/lti-1p3-tool/src/LtiDeepLink.php on line 33

This is being triggered by this line:

LtiConstants::DL_DATA => $this->deep_link_settings['data'],

in the getResponseJwt() function. 

I didn't submit a pull request on this, as I am not familiar enough with the deep link settings to know what the behavior should be if $this->deep_link_settings['data'] is undefined. Should it only set the LtiConstants::DL_DATA array key if the 'data' key of deep_link_settings exists? Or should it set the LtiConstants::DL_DATA key to null or empty string in that case?

**Comment by dbhynds** [comment]
I can look into this, but @zlayaAvocado or @pb-sobrien do either of you know off the top of your heads?

**Comment by pb-sobrien** [comment]
Hmmm. No idea. We don't use DL at all so it's never come up. Can also dig into it next week though.

**Comment by zlayaAvocado** [comment]
I am not sure as well, didnt work with deep linking before

**Comment by dbhynds** [comment]
@mattwright Can you provide a little more context? What does your code look like when you encounter this error?

We're not using this ourselves currently, but I manually tested it a while back. In our code, we were doing:

```php
if ($ltiMessageLaunch->isDeepLinkLaunch()) {
    $deepLink = $ltiMessageLaunch->getDeepLink();
}
```

I'm wondering if perhaps you're not doing the `isDeepLinkLaunch()` check first, so it's trying to use deep link settings from a launch that isn't a deep link launch. Is that what you're doing?

Reading through https://www.imsglobal.org/spec/lti-dl/v2p0/#deep-linking-request-message and the next section on deep link settings, it seems like the settings object is required for a deep link. Based on that, my interpretation of expected behavior, then, is that the library should throw an exception.

**Comment by mattwright** [comment]
@dbhynds -- Thanks for the link to the appropriate section of the docs. It show that 'data' is in fact an optional property of deep link settings, so I made a fix that I think is appropriate to the code base and submitted a pull request.

I also checked my code and this warning was being thrown on launches where $ltiMessageLaunch->isDeepLinkLaunch() returned true. Here is a sample of my deep link settings from the lti message launch data, which shows that the 'data' property is missing on at least some Canvas deep link request settings:

```json
{
    "https:\/\/purl.imsglobal.org\/spec\/lti-dl\/claim\/deep_linking_settings": {
        "deep_link_return_url": "REDACTED",
        "accept_types": [
            "ltiResourceLink"
        ],
        "accept_presentation_document_targets": [
            "iframe",
            "window"
        ],
        "accept_media_types": "application\/vnd.ims.lti.v1.ltilink",
        "auto_create": false,
        "accept_multiple": false,
        "validation_context": null,
        "errors": {
            "errors": []
        }
    },
}
```
